---
title: BT-Fragebögen
lang: de
---

ID of profile-store: `btfb`

Creator: IQB - Institut zur Qualitätsentwicklung im Bildungswesen

2 Profile definiert:

# BT Fragebögen - Aufgabe

ID of profile: [https://raw.githubusercontent.com/iqb-vocabs/p60/master/unit.json](https://raw.githubusercontent.com/iqb-vocabs/p60/master/unit.json)

| Name/Label | Typ | Parameter | ID Profil-Eintrag |
| :--- | :---: | :--- | :---: |
| Konstruktbereich | [Vokabular](https://w3id.org/iqb/v87/cq/) | url: 'https://w3id.org/iqb/v87/cq/', Einmalauswahl, Zeige nur erste Ebene, Dialogbox, Nummerierung unterdrückt | e2 |
| Aufgabenzeit | Zahl | Kommastellen: 0, Mindestwert: 0, Maximalwert: kein, als Sekunden | iqb_time_unit |
| Version | Text | Einzeilig, Sprache(n): de   | iqb_version |
| Fragebogen | [Vokabular](https://w3id.org/iqb/v85/ee/) | url: 'https://w3id.org/iqb/v85/ee/', Einmalauswahl, Dialogbox, Nummerierung unterdrückt | e3 |
| Quelle | Text | Mehrzeilig, Sprache(n): de   | iqb_copyright |
| Zuletzt genehmigt | [Vokabular](https://w3id.org/iqb/v37/zg/) | url: 'https://w3id.org/iqb/v37/zg/', Einmalauswahl, Dialogbox, Nummerierung unterdrückt | e4 |
| Schulstufe | [Vokabular](https://w3id.org/kim/educationalLevel/) | url: 'https://w3id.org/kim/educationalLevel/', Einmalauswahl, Dialogbox, Nummerierung unterdrückt | f5 |
| Transkript | Text | Mehrzeilig, Sprache(n): de   | iqb_transcript |

: {tbl-colwidths="[15,15,55,15]"}

# BT Fragebögen - Item

ID of profile: [https://raw.githubusercontent.com/iqb-vocabs/p60/master/item.json](https://raw.githubusercontent.com/iqb-vocabs/p60/master/item.json)

| Name/Label | Typ | Parameter | ID Profil-Eintrag |
| :--- | :---: | :--- | :---: |
| Variablenbezeichnung | Text | Mehrzeilig, Sprache(n): de   | iqb_var_name |
| Konstrukt | [Vokabular](https://w3id.org/iqb/v87/cq/) | url: 'https://w3id.org/iqb/v87/cq/', Einmalauswahl, Dialogbox, Nummerierung unterdrückt | w1 |

: {tbl-colwidths="[15,15,55,15]"}

